name = "CozyWarz SMP"
author = "CozyRamennoodle"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "411f93b28174ac406ce14d3ddad46e2233513d0407739cd929f9fccb42ac7f7a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.221"
