name = "CozyWarz SMP"
author = "CozyRamennoodle"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "db9db6cb3d1a97da5a90c2755ab948cafdd48c71677ff6b16b88a1505d49443a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
