name = "CozyWarz SMP"
author = "CozyRamennoodle"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "183fe7aef11479c519d3ab688f9459537fe515eda0aa2690a21da6e6c5d35953"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
